-- Tempahan Bilik Khas — skema Supabase
-- Semua akses melalui api/booking.js (service role). RLS dihidupkan tanpa polisi,
-- jadi kunci anon/publik tidak boleh membaca atau menulis apa-apa.

create extension if not exists btree_gist;

create table if not exists public.teachers (
  email       text primary key check (email = lower(email)),
  name        text not null,
  role        text not null default 'guru' check (role in ('guru','admin')),
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.rooms (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  location    text,
  capacity    int,
  active      boolean not null default true,
  sort_order  int not null default 0
);

create table if not exists public.bookings (
  id            uuid primary key default gen_random_uuid(),
  room_id       bigint not null references public.rooms(id),
  teacher_email text not null references public.teachers(email) on update cascade,
  booking_date  date not null,
  start_time    time not null,
  end_time      time not null,
  class_name    text,
  purpose       text,
  status        text not null default 'ACTIVE' check (status in ('ACTIVE','CANCELLED')),
  created_at    timestamptz not null default now(),
  cancelled_at  timestamptz,
  check (start_time < end_time),
  -- Tiada dua tempahan ACTIVE boleh bertindih bagi bilik yang sama.
  constraint bookings_no_overlap exclude using gist (
    room_id with =,
    tsrange(booking_date + start_time, booking_date + end_time) with &&
  ) where (status = 'ACTIVE')
);

create index if not exists bookings_date_idx on public.bookings (booking_date);
create index if not exists bookings_teacher_idx on public.bookings (teacher_email, booking_date);

-- Sekatan: room_id null = semua bilik; start_time/end_time null = sepanjang hari.
create table if not exists public.blocks (
  id          bigint generated by default as identity primary key,
  room_id     bigint references public.rooms(id),
  block_date  date not null,
  start_time  time,
  end_time    time,
  reason      text,
  created_at  timestamptz not null default now(),
  check ((start_time is null) = (end_time is null)),
  check (start_time is null or start_time < end_time)
);

create index if not exists blocks_date_idx on public.blocks (block_date);

-- Tolak tempahan yang jatuh dalam slot sekatan.
create or replace function public.reject_blocked_booking() returns trigger
language plpgsql as $$
declare
  b public.blocks;
begin
  if new.status <> 'ACTIVE' then
    return new;
  end if;
  select * into b from public.blocks
   where block_date = new.booking_date
     and (room_id is null or room_id = new.room_id)
     and (start_time is null or (start_time < new.end_time and end_time > new.start_time))
   limit 1;
  if found then
    raise exception using
      errcode = 'P0001',
      message = 'BLOCKED',
      detail  = coalesce(b.reason, 'Slot ini disekat oleh pentadbir.');
  end if;
  return new;
end $$;

drop trigger if exists bookings_reject_blocked on public.bookings;
create trigger bookings_reject_blocked
  before insert or update of room_id, booking_date, start_time, end_time, status
  on public.bookings
  for each row execute function public.reject_blocked_booking();

alter table public.teachers enable row level security;
alter table public.rooms    enable row level security;
alter table public.bookings enable row level security;
alter table public.blocks   enable row level security;

insert into public.rooms (name, sort_order) values
  ('Aula Perdana', 1),
  ('Dewan Lestari Jauhar', 2),
  ('Bidari Corner', 3),
  ('PSS', 4),
  ('Bilik PAK21', 5),
  ('Surau', 6)
on conflict (name) do nothing;
